# Generated by Django 3.1 on 2020-08-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='first_factor',
            field=models.CharField(blank=True, choices=[('password', 'en tapant un mot de passe'), ('email', 'en cliquant sur un lien reçu par email'), ('mfs', 'en utilisant mon compte Maisons France Services')], max_length=8),
        ),
        migrations.AddField(
            model_name='aidant',
            name='second_factor',
            field=models.CharField(blank=True, choices=[('sms', 'en tapant un code reçu par SMS'), ('call', 'en tapant un code reçu par appel téléphonique'), ('app', 'en utilisant une application mobile'), ('key', 'en utilisant une clé de sécurité')], max_length=8),
        ),
        migrations.AddField(
            model_name='aidant',
            name='has_completed_registration',
            field=models.BooleanField(default=False),
        ),
    ]
