# Generated by Django 3.1 on 2020-08-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants', '0002_add_flexauth_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='siret',
            field=models.CharField(blank=True, max_length=32, verbose_name='N° SIRET'),
        ),
        migrations.AlterField(
            model_name='aidant',
            name='has_completed_registration',
            field=models.BooleanField(default=False, verbose_name='a terminé son inscription'),
        ),
        migrations.AlterField(
            model_name='aidant',
            name='first_factor',
            field=models.CharField(blank=True, choices=[
                ('password', 'en tapant un mot de passe'),
                ('email', 'en cliquant sur un lien reçu par email')
            ], max_length=8, verbose_name='préfère se connecter'),
        ),
        migrations.AlterField(
            model_name='aidant',
            name='second_factor',
            field=models.CharField(blank=True, choices=[
                ('sms', 'en tapant un code reçu par SMS'),
                ('call', 'en tapant un code reçu par appel téléphonique'),
                ('app', 'en utilisant une application mobile'),
                ('key', 'en utilisant une clé de sécurité')
            ], max_length=8, verbose_name='confirme son identité'),
        ),
    ]
