# Generated by Django 3.1 on 2020-08-26 11:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('aidants', '0003_fix_field_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_firstname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prénom du contact'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_lastname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du contact'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse email du contact'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Téléphone du contact'),
        ),
    ]
