# Generated by Django 3.1 on 2020-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[

                migrations.CreateModel(
                    name='Journal',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('action', models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('update_email_usager', "L'email de l'usager a été modifié"), ('create_attestation', "Création d'une attestation"), ('create_autorisation', "Création d'une autorisation"), ('use_autorisation', "Utilisation d'une autorisation"), ('cancel_autorisation', "Révocation d'une autorisation")], max_length=30)),
                        ('initiator', models.TextField()),
                        ('creation_date', models.DateTimeField(auto_now_add=True)),
                        ('demarche', models.CharField(blank=True, max_length=100, null=True)),
                        ('usager', models.TextField(blank=True, null=True)),
                        ('duree', models.IntegerField(blank=True, null=True)),
                        ('access_token', models.TextField(blank=True, null=True)),
                        ('autorisation', models.IntegerField(blank=True, null=True)),
                        ('attestation_hash', models.CharField(blank=True, max_length=100, null=True)),
                        ('additional_information', models.TextField(blank=True, null=True)),
                        ('is_remote_mandat', models.BooleanField(default=False)),
                    ],
                    options={
                        'verbose_name': 'entrée de journal',
                        'verbose_name_plural': 'entrées de journal',
                        'db_table': 'aidants_connect_web_journal',
                    },
                ),

            ]
        )
    ]
