# Generated by Django 3.1 on 2020-08-11 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[

                migrations.CreateModel(
                    name='Usager',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('given_name', models.CharField(max_length=255, verbose_name='Prénom')),
                        ('family_name', models.CharField(max_length=255, verbose_name='Nom')),
                        ('preferred_username', models.CharField(blank=True, max_length=255)),
                        ('gender', models.CharField(choices=[('female', 'Femme'), ('male', 'Homme')], default='female', max_length=6, verbose_name='Genre')),
                        ('birthdate', models.DateField(verbose_name='Date de naissance')),
                        ('birthplace', models.CharField(blank=True, max_length=5, null=True, verbose_name='Lieu de naissance')),
                        ('birthcountry', models.CharField(default='99100', max_length=5, verbose_name='Pays de naissance')),
                        ('sub', models.TextField(unique=True)),
                        ('email', models.EmailField(default='noemailprovided@aidantconnect.beta.gouv.fr', max_length=254)),
                        ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                    ],
                    options={
                        'db_table': 'aidants_connect_web_usager',
                        'ordering': ['family_name', 'given_name'],
                    },
                ),

            ]
        )
    ]
